development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: pact_consumer_development
  pool: 5
  username: postgres
  password: Secret99
  template: template0
  port: 5434
test:
  host: localhost
  adapter: postgresql
  database: pact_consumer_test
  encoding: unicode
  pool: 5
  username: postgres
  password: Secret99
  template: template0
  port: 5434
